[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader_api = "0.11"
spin = "0.9"
uart_16550 = "0.4"
x86_64 = "0.15"
pic8259 = "0.11"
pc-keyboard = "0.7"
linked_list_allocator = "0.10"
